version: '0.1'

services:
  server:
    build: .
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
    volumes:
      - ./Client/build:/var/www/site/dev:ro
      - ./Server/api:/var/www/site/dev/api:ro

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'game'

  admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db